name: Deploy Functions in Production environment
 
on:
  push:
    branches: [main]
 
jobs:
  call-update-function:
    uses: ./.github/workflows/reusable-deploy-matrix.yml
    with:
      environment: main
      lambdas_base_path: "./src/"
    secrets: inherit